import { c as create_ssr_component, f as add_attribute } from "../../../chunks/ssr.js";
import "firebase/auth";
import "../../../chunks/firebase.js";
const css = {
  code: '.maincontainer.s-jZJiUkwef1J0.s-jZJiUkwef1J0{display:flex;flex-direction:column;align-items:center}[data-thq="thq-dropdown"].s-jZJiUkwef1J0:hover>[data-thq="thq-dropdown-list"].s-jZJiUkwef1J0{display:flex}.agm-voting-header.s-jZJiUkwef1J0.s-jZJiUkwef1J0{width:100%;height:150px;display:flex;max-width:1400px;min-width:1400px;align-self:center;align-items:center;justify-content:space-between}.agm-voting-btn-group.s-jZJiUkwef1J0.s-jZJiUkwef1J0{width:auto;height:auto;display:flex;align-items:center;border-radius:4px;flex-direction:row;justify-content:space-between;gap:30px}.log_out.s-jZJiUkwef1J0.s-jZJiUkwef1J0{color:#ffffff;width:auto;height:auto;font-size:30px;border-width:0px;margin-right:32px;text-decoration:none;background-color:#6ba3ab}.button.s-jZJiUkwef1J0.s-jZJiUkwef1J0{display:inline-block;padding:0.5rem 1rem;border-color:var(--dl-color-gray-black);border-radius:4px}.agm-voting-dropdown-toggle.s-jZJiUkwef1J0.s-jZJiUkwef1J0{fill:#595959;color:#ffffff;width:100%;display:inline-flex;align-items:center;padding-top:8px;padding-left:16px;border-radius:4px;padding-right:16px;padding-bottom:8px;justify-content:flex-start;background-color:#6ba3ab;cursor:pointer}.agm-voting-dropdown-list.s-jZJiUkwef1J0.s-jZJiUkwef1J0{top:102px;right:23.9%;height:auto;display:none;z-index:100;position:absolute;transition:0.3s;align-items:stretch;flex-direction:column;list-style-type:none;background-color:#6ba3ab;list-style-position:inside}.agm-voting-dropdown01.s-jZJiUkwef1J0.s-jZJiUkwef1J0{width:100%;cursor:pointer;height:100%;display:inline-block;position:relative;border-color:var(--dl-color-gray-black);border-width:1px;border-radius:var(--dl-radius-radius-radius4);text-decoration:none;background-color:#6ba3ab;border-bottom-width:0px;border-top-left-radius:var(--dl-radius-radius-radius4);border-top-right-radius:var(--dl-radius-radius-radius4);border-bottom-left-radius:0;border-bottom-right-radius:0}.agm-voting-dropdown-toggle01.s-jZJiUkwef1J0.s-jZJiUkwef1J0,.agm-voting-dropdown-toggle03.s-jZJiUkwef1J0.s-jZJiUkwef1J0{fill:#595959;color:#ffffff;width:100%;display:inline-flex;transition:0.3s;align-items:center;padding-top:8px;padding-left:16px;border-radius:4px;padding-right:16px;padding-bottom:8px;gap:10px}.agm-voting-text.s-jZJiUkwef1J0.s-jZJiUkwef1J0{width:96px;font-size:30px;font-style:normal;text-align:center;font-weight:500;margin-right:4px;vertical-align:middle}.agm-voting-text01.s-jZJiUkwef1J0.s-jZJiUkwef1J0,.agm-voting-text03.s-jZJiUkwef1J0.s-jZJiUkwef1J0{width:100%;cursor:pointer;display:flex;font-size:30px;font-style:normal;font-weight:500;color:white}.agm-voting-dropdown-toggle01.s-jZJiUkwef1J0.s-jZJiUkwef1J0:hover,.agm-voting-dropdown-toggle03.s-jZJiUkwef1J0.s-jZJiUkwef1J0:hover{fill:#fff;color:#fff;background-color:#595959}',
  map: null
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let content = "";
  $$result.css.add(css);
  return `<div class="maincontainer s-jZJiUkwef1J0"><header data-role="Header" class="agm-voting-header s-jZJiUkwef1J0"><img alt="logo" src="rnslogo.png" class="agm-voting-image Logo"> <div class="agm-voting-btn-group s-jZJiUkwef1J0"><div data-thq="thq-dropdown" class="drop_down_menu list-item agm-voting-dropdown s-jZJiUkwef1J0"><div data-thq="thq-dropdown-toggle" class="agm-voting-dropdown-toggle s-jZJiUkwef1J0"><span class="agm-voting-text s-jZJiUkwef1J0" data-svelte-h="svelte-efxkz1">Menu</span></div> <ul data-thq="thq-dropdown-list" class="agm-voting-dropdown-list s-jZJiUkwef1J0"><a href="Share Holders"><li data-thq="thq-dropdown" class="agm-voting-dropdown01 list-item s-jZJiUkwef1J0"><div data-thq="thq-dropdown-toggle" class="agm-voting-dropdown-toggle01 s-jZJiUkwef1J0"><i id="icon" class="icon fa-regular fa-user" style="color: #ffffff;"${add_attribute("this", content, 0)}></i> <span class="agm-voting-text01 s-jZJiUkwef1J0" data-svelte-h="svelte-131xnp1">Share Holders</span></div></li></a> <a href="Voting"><li data-thq="thq-dropdown" class="agm-voting-dropdown03 list-item"><div data-thq="thq-dropdown-toggle" class="agm-voting-dropdown-toggle03 s-jZJiUkwef1J0"><i class="icon fa-solid fa-square-poll-vertical" style="color: #ffffff;"></i> <span class="agm-voting-text03 s-jZJiUkwef1J0" data-svelte-h="svelte-1ua6xx4">Voting</span></div></li></a></ul></div> <button class="log_out button s-jZJiUkwef1J0" data-svelte-h="svelte-hvegq5">Log Out</button></div></header> </div>`;
});
export {
  Page as default
};
